// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActorAddress struct {
	NodeInstanceId       uint64   `protobuf:"varint,1,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	Handle               uint32   `protobuf:"varint,2,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorAddress) Reset()         { *m = ActorAddress{} }
func (m *ActorAddress) String() string { return proto.CompactTextString(m) }
func (*ActorAddress) ProtoMessage()    {}
func (*ActorAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *ActorAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorAddress.Unmarshal(m, b)
}
func (m *ActorAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorAddress.Marshal(b, m, deterministic)
}
func (m *ActorAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorAddress.Merge(m, src)
}
func (m *ActorAddress) XXX_Size() int {
	return xxx_messageInfo_ActorAddress.Size(m)
}
func (m *ActorAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ActorAddress proto.InternalMessageInfo

func (m *ActorAddress) GetNodeInstanceId() uint64 {
	if m != nil {
		return m.NodeInstanceId
	}
	return 0
}

func (m *ActorAddress) GetHandle() uint32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type GameInfo struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,json=gameId,proto3" json:"GameId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=State,json=state,proto3" json:"State,omitempty"`
	YourMove             bool     `protobuf:"varint,4,opt,name=YourMove,json=yourMove,proto3" json:"YourMove,omitempty"`
	GameStarter          bool     `protobuf:"varint,5,opt,name=GameStarter,json=gameStarter,proto3" json:"GameStarter,omitempty"`
	UserNames            []string `protobuf:"bytes,6,rep,name=UserNames,json=usernames,proto3" json:"UserNames,omitempty"`
	NumMoves             int32    `protobuf:"varint,7,opt,name=NumMoves,json=numMoves,proto3" json:"NumMoves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameInfo) Reset()         { *m = GameInfo{} }
func (m *GameInfo) String() string { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()    {}
func (*GameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *GameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfo.Unmarshal(m, b)
}
func (m *GameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfo.Marshal(b, m, deterministic)
}
func (m *GameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfo.Merge(m, src)
}
func (m *GameInfo) XXX_Size() int {
	return xxx_messageInfo_GameInfo.Size(m)
}
func (m *GameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfo proto.InternalMessageInfo

func (m *GameInfo) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *GameInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GameInfo) GetYourMove() bool {
	if m != nil {
		return m.YourMove
	}
	return false
}

func (m *GameInfo) GetGameStarter() bool {
	if m != nil {
		return m.GameStarter
	}
	return false
}

func (m *GameInfo) GetUserNames() []string {
	if m != nil {
		return m.UserNames
	}
	return nil
}

func (m *GameInfo) GetNumMoves() int32 {
	if m != nil {
		return m.NumMoves
	}
	return 0
}

type MoveStep struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveStep) Reset()         { *m = MoveStep{} }
func (m *MoveStep) String() string { return proto.CompactTextString(m) }
func (*MoveStep) ProtoMessage()    {}
func (*MoveStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *MoveStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveStep.Unmarshal(m, b)
}
func (m *MoveStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveStep.Marshal(b, m, deterministic)
}
func (m *MoveStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveStep.Merge(m, src)
}
func (m *MoveStep) XXX_Size() int {
	return xxx_messageInfo_MoveStep.Size(m)
}
func (m *MoveStep) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveStep.DiscardUnknown(m)
}

var xxx_messageInfo_MoveStep proto.InternalMessageInfo

func (m *MoveStep) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveStep) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type GameMoves struct {
	Summary              *GameInfo   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Moves                []*MoveStep `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GameMoves) Reset()         { *m = GameMoves{} }
func (m *GameMoves) String() string { return proto.CompactTextString(m) }
func (*GameMoves) ProtoMessage()    {}
func (*GameMoves) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *GameMoves) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMoves.Unmarshal(m, b)
}
func (m *GameMoves) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMoves.Marshal(b, m, deterministic)
}
func (m *GameMoves) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMoves.Merge(m, src)
}
func (m *GameMoves) XXX_Size() int {
	return xxx_messageInfo_GameMoves.Size(m)
}
func (m *GameMoves) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMoves.DiscardUnknown(m)
}

var xxx_messageInfo_GameMoves proto.InternalMessageInfo

func (m *GameMoves) GetSummary() *GameInfo {
	if m != nil {
		return m.Summary
	}
	return nil
}

func (m *GameMoves) GetMoves() []*MoveStep {
	if m != nil {
		return m.Moves
	}
	return nil
}

type AvailableGame struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,json=gameId,proto3" json:"GameId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableGame) Reset()         { *m = AvailableGame{} }
func (m *AvailableGame) String() string { return proto.CompactTextString(m) }
func (*AvailableGame) ProtoMessage()    {}
func (*AvailableGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *AvailableGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableGame.Unmarshal(m, b)
}
func (m *AvailableGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableGame.Marshal(b, m, deterministic)
}
func (m *AvailableGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableGame.Merge(m, src)
}
func (m *AvailableGame) XXX_Size() int {
	return xxx_messageInfo_AvailableGame.Size(m)
}
func (m *AvailableGame) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableGame.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableGame proto.InternalMessageInfo

func (m *AvailableGame) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *AvailableGame) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ManagerNewGameRequest struct {
	Name                 string        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Player               *ActorAddress `protobuf:"bytes,2,opt,name=Player,proto3" json:"Player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ManagerNewGameRequest) Reset()         { *m = ManagerNewGameRequest{} }
func (m *ManagerNewGameRequest) String() string { return proto.CompactTextString(m) }
func (*ManagerNewGameRequest) ProtoMessage()    {}
func (*ManagerNewGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *ManagerNewGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerNewGameRequest.Unmarshal(m, b)
}
func (m *ManagerNewGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerNewGameRequest.Marshal(b, m, deterministic)
}
func (m *ManagerNewGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerNewGameRequest.Merge(m, src)
}
func (m *ManagerNewGameRequest) XXX_Size() int {
	return xxx_messageInfo_ManagerNewGameRequest.Size(m)
}
func (m *ManagerNewGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerNewGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerNewGameRequest proto.InternalMessageInfo

func (m *ManagerNewGameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ManagerNewGameRequest) GetPlayer() *ActorAddress {
	if m != nil {
		return m.Player
	}
	return nil
}

type ManagerNewGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerNewGameResponse) Reset()         { *m = ManagerNewGameResponse{} }
func (m *ManagerNewGameResponse) String() string { return proto.CompactTextString(m) }
func (*ManagerNewGameResponse) ProtoMessage()    {}
func (*ManagerNewGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *ManagerNewGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerNewGameResponse.Unmarshal(m, b)
}
func (m *ManagerNewGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerNewGameResponse.Marshal(b, m, deterministic)
}
func (m *ManagerNewGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerNewGameResponse.Merge(m, src)
}
func (m *ManagerNewGameResponse) XXX_Size() int {
	return xxx_messageInfo_ManagerNewGameResponse.Size(m)
}
func (m *ManagerNewGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerNewGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerNewGameResponse proto.InternalMessageInfo

type ManagerGetGameRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerGetGameRequest) Reset()         { *m = ManagerGetGameRequest{} }
func (m *ManagerGetGameRequest) String() string { return proto.CompactTextString(m) }
func (*ManagerGetGameRequest) ProtoMessage()    {}
func (*ManagerGetGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7}
}

func (m *ManagerGetGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerGetGameRequest.Unmarshal(m, b)
}
func (m *ManagerGetGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerGetGameRequest.Marshal(b, m, deterministic)
}
func (m *ManagerGetGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerGetGameRequest.Merge(m, src)
}
func (m *ManagerGetGameRequest) XXX_Size() int {
	return xxx_messageInfo_ManagerGetGameRequest.Size(m)
}
func (m *ManagerGetGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerGetGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerGetGameRequest proto.InternalMessageInfo

func (m *ManagerGetGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type ManagerGetGameResponse struct {
	Game                 *ActorAddress `protobuf:"bytes,1,opt,name=Game,proto3" json:"Game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ManagerGetGameResponse) Reset()         { *m = ManagerGetGameResponse{} }
func (m *ManagerGetGameResponse) String() string { return proto.CompactTextString(m) }
func (*ManagerGetGameResponse) ProtoMessage()    {}
func (*ManagerGetGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{8}
}

func (m *ManagerGetGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerGetGameResponse.Unmarshal(m, b)
}
func (m *ManagerGetGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerGetGameResponse.Marshal(b, m, deterministic)
}
func (m *ManagerGetGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerGetGameResponse.Merge(m, src)
}
func (m *ManagerGetGameResponse) XXX_Size() int {
	return xxx_messageInfo_ManagerGetGameResponse.Size(m)
}
func (m *ManagerGetGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerGetGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerGetGameResponse proto.InternalMessageInfo

func (m *ManagerGetGameResponse) GetGame() *ActorAddress {
	if m != nil {
		return m.Game
	}
	return nil
}

type ManagerGameListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerGameListRequest) Reset()         { *m = ManagerGameListRequest{} }
func (m *ManagerGameListRequest) String() string { return proto.CompactTextString(m) }
func (*ManagerGameListRequest) ProtoMessage()    {}
func (*ManagerGameListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{9}
}

func (m *ManagerGameListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerGameListRequest.Unmarshal(m, b)
}
func (m *ManagerGameListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerGameListRequest.Marshal(b, m, deterministic)
}
func (m *ManagerGameListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerGameListRequest.Merge(m, src)
}
func (m *ManagerGameListRequest) XXX_Size() int {
	return xxx_messageInfo_ManagerGameListRequest.Size(m)
}
func (m *ManagerGameListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerGameListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerGameListRequest proto.InternalMessageInfo

type ManagerGameListResponse struct {
	Games                []*AvailableGame `protobuf:"bytes,1,rep,name=Games,proto3" json:"Games,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ManagerGameListResponse) Reset()         { *m = ManagerGameListResponse{} }
func (m *ManagerGameListResponse) String() string { return proto.CompactTextString(m) }
func (*ManagerGameListResponse) ProtoMessage()    {}
func (*ManagerGameListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{10}
}

func (m *ManagerGameListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerGameListResponse.Unmarshal(m, b)
}
func (m *ManagerGameListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerGameListResponse.Marshal(b, m, deterministic)
}
func (m *ManagerGameListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerGameListResponse.Merge(m, src)
}
func (m *ManagerGameListResponse) XXX_Size() int {
	return xxx_messageInfo_ManagerGameListResponse.Size(m)
}
func (m *ManagerGameListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerGameListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerGameListResponse proto.InternalMessageInfo

func (m *ManagerGameListResponse) GetGames() []*AvailableGame {
	if m != nil {
		return m.Games
	}
	return nil
}

type ManagerFreeGameRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerFreeGameRequest) Reset()         { *m = ManagerFreeGameRequest{} }
func (m *ManagerFreeGameRequest) String() string { return proto.CompactTextString(m) }
func (*ManagerFreeGameRequest) ProtoMessage()    {}
func (*ManagerFreeGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{11}
}

func (m *ManagerFreeGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerFreeGameRequest.Unmarshal(m, b)
}
func (m *ManagerFreeGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerFreeGameRequest.Marshal(b, m, deterministic)
}
func (m *ManagerFreeGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerFreeGameRequest.Merge(m, src)
}
func (m *ManagerFreeGameRequest) XXX_Size() int {
	return xxx_messageInfo_ManagerFreeGameRequest.Size(m)
}
func (m *ManagerFreeGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerFreeGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerFreeGameRequest proto.InternalMessageInfo

func (m *ManagerFreeGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type ManagerFreeGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerFreeGameResponse) Reset()         { *m = ManagerFreeGameResponse{} }
func (m *ManagerFreeGameResponse) String() string { return proto.CompactTextString(m) }
func (*ManagerFreeGameResponse) ProtoMessage()    {}
func (*ManagerFreeGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{12}
}

func (m *ManagerFreeGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerFreeGameResponse.Unmarshal(m, b)
}
func (m *ManagerFreeGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerFreeGameResponse.Marshal(b, m, deterministic)
}
func (m *ManagerFreeGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerFreeGameResponse.Merge(m, src)
}
func (m *ManagerFreeGameResponse) XXX_Size() int {
	return xxx_messageInfo_ManagerFreeGameResponse.Size(m)
}
func (m *ManagerFreeGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerFreeGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerFreeGameResponse proto.InternalMessageInfo

type PlayerSetNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSetNameRequest) Reset()         { *m = PlayerSetNameRequest{} }
func (m *PlayerSetNameRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerSetNameRequest) ProtoMessage()    {}
func (*PlayerSetNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{13}
}

func (m *PlayerSetNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSetNameRequest.Unmarshal(m, b)
}
func (m *PlayerSetNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSetNameRequest.Marshal(b, m, deterministic)
}
func (m *PlayerSetNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSetNameRequest.Merge(m, src)
}
func (m *PlayerSetNameRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerSetNameRequest.Size(m)
}
func (m *PlayerSetNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSetNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSetNameRequest proto.InternalMessageInfo

func (m *PlayerSetNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PlayerSetNameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSetNameResponse) Reset()         { *m = PlayerSetNameResponse{} }
func (m *PlayerSetNameResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerSetNameResponse) ProtoMessage()    {}
func (*PlayerSetNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{14}
}

func (m *PlayerSetNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSetNameResponse.Unmarshal(m, b)
}
func (m *PlayerSetNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSetNameResponse.Marshal(b, m, deterministic)
}
func (m *PlayerSetNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSetNameResponse.Merge(m, src)
}
func (m *PlayerSetNameResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerSetNameResponse.Size(m)
}
func (m *PlayerSetNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSetNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSetNameResponse proto.InternalMessageInfo

type PlayerIndexRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerIndexRequest) Reset()         { *m = PlayerIndexRequest{} }
func (m *PlayerIndexRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerIndexRequest) ProtoMessage()    {}
func (*PlayerIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{15}
}

func (m *PlayerIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerIndexRequest.Unmarshal(m, b)
}
func (m *PlayerIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerIndexRequest.Marshal(b, m, deterministic)
}
func (m *PlayerIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerIndexRequest.Merge(m, src)
}
func (m *PlayerIndexRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerIndexRequest.Size(m)
}
func (m *PlayerIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerIndexRequest proto.InternalMessageInfo

type PlayerIndexResponse struct {
	Games                []*GameInfo      `protobuf:"bytes,1,rep,name=Games,json=games,proto3" json:"Games,omitempty"`
	Availables           []*AvailableGame `protobuf:"bytes,2,rep,name=Availables,json=availables,proto3" json:"Availables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlayerIndexResponse) Reset()         { *m = PlayerIndexResponse{} }
func (m *PlayerIndexResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerIndexResponse) ProtoMessage()    {}
func (*PlayerIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{16}
}

func (m *PlayerIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerIndexResponse.Unmarshal(m, b)
}
func (m *PlayerIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerIndexResponse.Marshal(b, m, deterministic)
}
func (m *PlayerIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerIndexResponse.Merge(m, src)
}
func (m *PlayerIndexResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerIndexResponse.Size(m)
}
func (m *PlayerIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerIndexResponse proto.InternalMessageInfo

func (m *PlayerIndexResponse) GetGames() []*GameInfo {
	if m != nil {
		return m.Games
	}
	return nil
}

func (m *PlayerIndexResponse) GetAvailables() []*AvailableGame {
	if m != nil {
		return m.Availables
	}
	return nil
}

type PlayerCreateGameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCreateGameRequest) Reset()         { *m = PlayerCreateGameRequest{} }
func (m *PlayerCreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateGameRequest) ProtoMessage()    {}
func (*PlayerCreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{17}
}

func (m *PlayerCreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateGameRequest.Unmarshal(m, b)
}
func (m *PlayerCreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateGameRequest.Marshal(b, m, deterministic)
}
func (m *PlayerCreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateGameRequest.Merge(m, src)
}
func (m *PlayerCreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateGameRequest.Size(m)
}
func (m *PlayerCreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateGameRequest proto.InternalMessageInfo

type PlayerCreateGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCreateGameResponse) Reset()         { *m = PlayerCreateGameResponse{} }
func (m *PlayerCreateGameResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateGameResponse) ProtoMessage()    {}
func (*PlayerCreateGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{18}
}

func (m *PlayerCreateGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateGameResponse.Unmarshal(m, b)
}
func (m *PlayerCreateGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateGameResponse.Marshal(b, m, deterministic)
}
func (m *PlayerCreateGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateGameResponse.Merge(m, src)
}
func (m *PlayerCreateGameResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateGameResponse.Size(m)
}
func (m *PlayerCreateGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateGameResponse proto.InternalMessageInfo

type PlayerGetMovesRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerGetMovesRequest) Reset()         { *m = PlayerGetMovesRequest{} }
func (m *PlayerGetMovesRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerGetMovesRequest) ProtoMessage()    {}
func (*PlayerGetMovesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{19}
}

func (m *PlayerGetMovesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerGetMovesRequest.Unmarshal(m, b)
}
func (m *PlayerGetMovesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerGetMovesRequest.Marshal(b, m, deterministic)
}
func (m *PlayerGetMovesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerGetMovesRequest.Merge(m, src)
}
func (m *PlayerGetMovesRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerGetMovesRequest.Size(m)
}
func (m *PlayerGetMovesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerGetMovesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerGetMovesRequest proto.InternalMessageInfo

func (m *PlayerGetMovesRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type PlayerGetMovesResponse struct {
	Moves                *GameMoves `protobuf:"bytes,1,opt,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlayerGetMovesResponse) Reset()         { *m = PlayerGetMovesResponse{} }
func (m *PlayerGetMovesResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerGetMovesResponse) ProtoMessage()    {}
func (*PlayerGetMovesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{20}
}

func (m *PlayerGetMovesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerGetMovesResponse.Unmarshal(m, b)
}
func (m *PlayerGetMovesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerGetMovesResponse.Marshal(b, m, deterministic)
}
func (m *PlayerGetMovesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerGetMovesResponse.Merge(m, src)
}
func (m *PlayerGetMovesResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerGetMovesResponse.Size(m)
}
func (m *PlayerGetMovesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerGetMovesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerGetMovesResponse proto.InternalMessageInfo

func (m *PlayerGetMovesResponse) GetMoves() *GameMoves {
	if m != nil {
		return m.Moves
	}
	return nil
}

type PlayerMakeMoveRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMakeMoveRequest) Reset()         { *m = PlayerMakeMoveRequest{} }
func (m *PlayerMakeMoveRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerMakeMoveRequest) ProtoMessage()    {}
func (*PlayerMakeMoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{21}
}

func (m *PlayerMakeMoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMakeMoveRequest.Unmarshal(m, b)
}
func (m *PlayerMakeMoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMakeMoveRequest.Marshal(b, m, deterministic)
}
func (m *PlayerMakeMoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMakeMoveRequest.Merge(m, src)
}
func (m *PlayerMakeMoveRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerMakeMoveRequest.Size(m)
}
func (m *PlayerMakeMoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMakeMoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMakeMoveRequest proto.InternalMessageInfo

func (m *PlayerMakeMoveRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *PlayerMakeMoveRequest) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PlayerMakeMoveRequest) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PlayerMakeMoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMakeMoveResponse) Reset()         { *m = PlayerMakeMoveResponse{} }
func (m *PlayerMakeMoveResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerMakeMoveResponse) ProtoMessage()    {}
func (*PlayerMakeMoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{22}
}

func (m *PlayerMakeMoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMakeMoveResponse.Unmarshal(m, b)
}
func (m *PlayerMakeMoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMakeMoveResponse.Marshal(b, m, deterministic)
}
func (m *PlayerMakeMoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMakeMoveResponse.Merge(m, src)
}
func (m *PlayerMakeMoveResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerMakeMoveResponse.Size(m)
}
func (m *PlayerMakeMoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMakeMoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMakeMoveResponse proto.InternalMessageInfo

type PlayerJoinRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerJoinRequest) Reset()         { *m = PlayerJoinRequest{} }
func (m *PlayerJoinRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerJoinRequest) ProtoMessage()    {}
func (*PlayerJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{23}
}

func (m *PlayerJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoinRequest.Unmarshal(m, b)
}
func (m *PlayerJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoinRequest.Marshal(b, m, deterministic)
}
func (m *PlayerJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoinRequest.Merge(m, src)
}
func (m *PlayerJoinRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerJoinRequest.Size(m)
}
func (m *PlayerJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoinRequest proto.InternalMessageInfo

func (m *PlayerJoinRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type PlayerJoinResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerJoinResponse) Reset()         { *m = PlayerJoinResponse{} }
func (m *PlayerJoinResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerJoinResponse) ProtoMessage()    {}
func (*PlayerJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{24}
}

func (m *PlayerJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoinResponse.Unmarshal(m, b)
}
func (m *PlayerJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoinResponse.Marshal(b, m, deterministic)
}
func (m *PlayerJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoinResponse.Merge(m, src)
}
func (m *PlayerJoinResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerJoinResponse.Size(m)
}
func (m *PlayerJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoinResponse proto.InternalMessageInfo

type PlayerOnJoinGameRequest struct {
	GameId               string        `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Addr                 *ActorAddress `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerOnJoinGameRequest) Reset()         { *m = PlayerOnJoinGameRequest{} }
func (m *PlayerOnJoinGameRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerOnJoinGameRequest) ProtoMessage()    {}
func (*PlayerOnJoinGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{25}
}

func (m *PlayerOnJoinGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerOnJoinGameRequest.Unmarshal(m, b)
}
func (m *PlayerOnJoinGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerOnJoinGameRequest.Marshal(b, m, deterministic)
}
func (m *PlayerOnJoinGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerOnJoinGameRequest.Merge(m, src)
}
func (m *PlayerOnJoinGameRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerOnJoinGameRequest.Size(m)
}
func (m *PlayerOnJoinGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerOnJoinGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerOnJoinGameRequest proto.InternalMessageInfo

func (m *PlayerOnJoinGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *PlayerOnJoinGameRequest) GetAddr() *ActorAddress {
	if m != nil {
		return m.Addr
	}
	return nil
}

type PlayerOnJoinGameResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerOnJoinGameResponse) Reset()         { *m = PlayerOnJoinGameResponse{} }
func (m *PlayerOnJoinGameResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerOnJoinGameResponse) ProtoMessage()    {}
func (*PlayerOnJoinGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{26}
}

func (m *PlayerOnJoinGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerOnJoinGameResponse.Unmarshal(m, b)
}
func (m *PlayerOnJoinGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerOnJoinGameResponse.Marshal(b, m, deterministic)
}
func (m *PlayerOnJoinGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerOnJoinGameResponse.Merge(m, src)
}
func (m *PlayerOnJoinGameResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerOnJoinGameResponse.Size(m)
}
func (m *PlayerOnJoinGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerOnJoinGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerOnJoinGameResponse proto.InternalMessageInfo

func (m *PlayerOnJoinGameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PlayerOnLeaveGameRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerOnLeaveGameRequest) Reset()         { *m = PlayerOnLeaveGameRequest{} }
func (m *PlayerOnLeaveGameRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerOnLeaveGameRequest) ProtoMessage()    {}
func (*PlayerOnLeaveGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{27}
}

func (m *PlayerOnLeaveGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerOnLeaveGameRequest.Unmarshal(m, b)
}
func (m *PlayerOnLeaveGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerOnLeaveGameRequest.Marshal(b, m, deterministic)
}
func (m *PlayerOnLeaveGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerOnLeaveGameRequest.Merge(m, src)
}
func (m *PlayerOnLeaveGameRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerOnLeaveGameRequest.Size(m)
}
func (m *PlayerOnLeaveGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerOnLeaveGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerOnLeaveGameRequest proto.InternalMessageInfo

func (m *PlayerOnLeaveGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type PlayerOnLeaveGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerOnLeaveGameResponse) Reset()         { *m = PlayerOnLeaveGameResponse{} }
func (m *PlayerOnLeaveGameResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerOnLeaveGameResponse) ProtoMessage()    {}
func (*PlayerOnLeaveGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{28}
}

func (m *PlayerOnLeaveGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerOnLeaveGameResponse.Unmarshal(m, b)
}
func (m *PlayerOnLeaveGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerOnLeaveGameResponse.Marshal(b, m, deterministic)
}
func (m *PlayerOnLeaveGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerOnLeaveGameResponse.Merge(m, src)
}
func (m *PlayerOnLeaveGameResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerOnLeaveGameResponse.Size(m)
}
func (m *PlayerOnLeaveGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerOnLeaveGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerOnLeaveGameResponse proto.InternalMessageInfo

type GameJoinRequest struct {
	Player               *ActorAddress `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameJoinRequest) Reset()         { *m = GameJoinRequest{} }
func (m *GameJoinRequest) String() string { return proto.CompactTextString(m) }
func (*GameJoinRequest) ProtoMessage()    {}
func (*GameJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{29}
}

func (m *GameJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameJoinRequest.Unmarshal(m, b)
}
func (m *GameJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameJoinRequest.Marshal(b, m, deterministic)
}
func (m *GameJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameJoinRequest.Merge(m, src)
}
func (m *GameJoinRequest) XXX_Size() int {
	return xxx_messageInfo_GameJoinRequest.Size(m)
}
func (m *GameJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameJoinRequest proto.InternalMessageInfo

func (m *GameJoinRequest) GetPlayer() *ActorAddress {
	if m != nil {
		return m.Player
	}
	return nil
}

type GameJoinResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameJoinResponse) Reset()         { *m = GameJoinResponse{} }
func (m *GameJoinResponse) String() string { return proto.CompactTextString(m) }
func (*GameJoinResponse) ProtoMessage()    {}
func (*GameJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{30}
}

func (m *GameJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameJoinResponse.Unmarshal(m, b)
}
func (m *GameJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameJoinResponse.Marshal(b, m, deterministic)
}
func (m *GameJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameJoinResponse.Merge(m, src)
}
func (m *GameJoinResponse) XXX_Size() int {
	return xxx_messageInfo_GameJoinResponse.Size(m)
}
func (m *GameJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameJoinResponse proto.InternalMessageInfo

type GameLeaveRequest struct {
	Player               *ActorAddress `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameLeaveRequest) Reset()         { *m = GameLeaveRequest{} }
func (m *GameLeaveRequest) String() string { return proto.CompactTextString(m) }
func (*GameLeaveRequest) ProtoMessage()    {}
func (*GameLeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{31}
}

func (m *GameLeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameLeaveRequest.Unmarshal(m, b)
}
func (m *GameLeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameLeaveRequest.Marshal(b, m, deterministic)
}
func (m *GameLeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameLeaveRequest.Merge(m, src)
}
func (m *GameLeaveRequest) XXX_Size() int {
	return xxx_messageInfo_GameLeaveRequest.Size(m)
}
func (m *GameLeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameLeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameLeaveRequest proto.InternalMessageInfo

func (m *GameLeaveRequest) GetPlayer() *ActorAddress {
	if m != nil {
		return m.Player
	}
	return nil
}

type GameLeaveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameLeaveResponse) Reset()         { *m = GameLeaveResponse{} }
func (m *GameLeaveResponse) String() string { return proto.CompactTextString(m) }
func (*GameLeaveResponse) ProtoMessage()    {}
func (*GameLeaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{32}
}

func (m *GameLeaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameLeaveResponse.Unmarshal(m, b)
}
func (m *GameLeaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameLeaveResponse.Marshal(b, m, deterministic)
}
func (m *GameLeaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameLeaveResponse.Merge(m, src)
}
func (m *GameLeaveResponse) XXX_Size() int {
	return xxx_messageInfo_GameLeaveResponse.Size(m)
}
func (m *GameLeaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameLeaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameLeaveResponse proto.InternalMessageInfo

type GameInfoRequest struct {
	Player               *ActorAddress `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameInfoRequest) Reset()         { *m = GameInfoRequest{} }
func (m *GameInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GameInfoRequest) ProtoMessage()    {}
func (*GameInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{33}
}

func (m *GameInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfoRequest.Unmarshal(m, b)
}
func (m *GameInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfoRequest.Marshal(b, m, deterministic)
}
func (m *GameInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfoRequest.Merge(m, src)
}
func (m *GameInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GameInfoRequest.Size(m)
}
func (m *GameInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfoRequest proto.InternalMessageInfo

func (m *GameInfoRequest) GetPlayer() *ActorAddress {
	if m != nil {
		return m.Player
	}
	return nil
}

type GameInfoResponse struct {
	Game                 *GameInfo `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameInfoResponse) Reset()         { *m = GameInfoResponse{} }
func (m *GameInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GameInfoResponse) ProtoMessage()    {}
func (*GameInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{34}
}

func (m *GameInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfoResponse.Unmarshal(m, b)
}
func (m *GameInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfoResponse.Marshal(b, m, deterministic)
}
func (m *GameInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfoResponse.Merge(m, src)
}
func (m *GameInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GameInfoResponse.Size(m)
}
func (m *GameInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfoResponse proto.InternalMessageInfo

func (m *GameInfoResponse) GetGame() *GameInfo {
	if m != nil {
		return m.Game
	}
	return nil
}

type GameGetMovesRequest struct {
	Player               *ActorAddress `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameGetMovesRequest) Reset()         { *m = GameGetMovesRequest{} }
func (m *GameGetMovesRequest) String() string { return proto.CompactTextString(m) }
func (*GameGetMovesRequest) ProtoMessage()    {}
func (*GameGetMovesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{35}
}

func (m *GameGetMovesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameGetMovesRequest.Unmarshal(m, b)
}
func (m *GameGetMovesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameGetMovesRequest.Marshal(b, m, deterministic)
}
func (m *GameGetMovesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameGetMovesRequest.Merge(m, src)
}
func (m *GameGetMovesRequest) XXX_Size() int {
	return xxx_messageInfo_GameGetMovesRequest.Size(m)
}
func (m *GameGetMovesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameGetMovesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameGetMovesRequest proto.InternalMessageInfo

func (m *GameGetMovesRequest) GetPlayer() *ActorAddress {
	if m != nil {
		return m.Player
	}
	return nil
}

type GameGetMovesResponse struct {
	Info                 *GameMoves `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GameGetMovesResponse) Reset()         { *m = GameGetMovesResponse{} }
func (m *GameGetMovesResponse) String() string { return proto.CompactTextString(m) }
func (*GameGetMovesResponse) ProtoMessage()    {}
func (*GameGetMovesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{36}
}

func (m *GameGetMovesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameGetMovesResponse.Unmarshal(m, b)
}
func (m *GameGetMovesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameGetMovesResponse.Marshal(b, m, deterministic)
}
func (m *GameGetMovesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameGetMovesResponse.Merge(m, src)
}
func (m *GameGetMovesResponse) XXX_Size() int {
	return xxx_messageInfo_GameGetMovesResponse.Size(m)
}
func (m *GameGetMovesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameGetMovesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameGetMovesResponse proto.InternalMessageInfo

func (m *GameGetMovesResponse) GetInfo() *GameMoves {
	if m != nil {
		return m.Info
	}
	return nil
}

type GameMakeMoveRequest struct {
	Player               *ActorAddress `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	X                    int32         `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32         `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameMakeMoveRequest) Reset()         { *m = GameMakeMoveRequest{} }
func (m *GameMakeMoveRequest) String() string { return proto.CompactTextString(m) }
func (*GameMakeMoveRequest) ProtoMessage()    {}
func (*GameMakeMoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{37}
}

func (m *GameMakeMoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMakeMoveRequest.Unmarshal(m, b)
}
func (m *GameMakeMoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMakeMoveRequest.Marshal(b, m, deterministic)
}
func (m *GameMakeMoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMakeMoveRequest.Merge(m, src)
}
func (m *GameMakeMoveRequest) XXX_Size() int {
	return xxx_messageInfo_GameMakeMoveRequest.Size(m)
}
func (m *GameMakeMoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMakeMoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameMakeMoveRequest proto.InternalMessageInfo

func (m *GameMakeMoveRequest) GetPlayer() *ActorAddress {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *GameMakeMoveRequest) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GameMakeMoveRequest) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type GameMakeMoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameMakeMoveResponse) Reset()         { *m = GameMakeMoveResponse{} }
func (m *GameMakeMoveResponse) String() string { return proto.CompactTextString(m) }
func (*GameMakeMoveResponse) ProtoMessage()    {}
func (*GameMakeMoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{38}
}

func (m *GameMakeMoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMakeMoveResponse.Unmarshal(m, b)
}
func (m *GameMakeMoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMakeMoveResponse.Marshal(b, m, deterministic)
}
func (m *GameMakeMoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMakeMoveResponse.Merge(m, src)
}
func (m *GameMakeMoveResponse) XXX_Size() int {
	return xxx_messageInfo_GameMakeMoveResponse.Size(m)
}
func (m *GameMakeMoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMakeMoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameMakeMoveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ActorAddress)(nil), "message.ActorAddress")
	proto.RegisterType((*GameInfo)(nil), "message.GameInfo")
	proto.RegisterType((*MoveStep)(nil), "message.MoveStep")
	proto.RegisterType((*GameMoves)(nil), "message.GameMoves")
	proto.RegisterType((*AvailableGame)(nil), "message.AvailableGame")
	proto.RegisterType((*ManagerNewGameRequest)(nil), "message.ManagerNewGameRequest")
	proto.RegisterType((*ManagerNewGameResponse)(nil), "message.ManagerNewGameResponse")
	proto.RegisterType((*ManagerGetGameRequest)(nil), "message.ManagerGetGameRequest")
	proto.RegisterType((*ManagerGetGameResponse)(nil), "message.ManagerGetGameResponse")
	proto.RegisterType((*ManagerGameListRequest)(nil), "message.ManagerGameListRequest")
	proto.RegisterType((*ManagerGameListResponse)(nil), "message.ManagerGameListResponse")
	proto.RegisterType((*ManagerFreeGameRequest)(nil), "message.ManagerFreeGameRequest")
	proto.RegisterType((*ManagerFreeGameResponse)(nil), "message.ManagerFreeGameResponse")
	proto.RegisterType((*PlayerSetNameRequest)(nil), "message.PlayerSetNameRequest")
	proto.RegisterType((*PlayerSetNameResponse)(nil), "message.PlayerSetNameResponse")
	proto.RegisterType((*PlayerIndexRequest)(nil), "message.PlayerIndexRequest")
	proto.RegisterType((*PlayerIndexResponse)(nil), "message.PlayerIndexResponse")
	proto.RegisterType((*PlayerCreateGameRequest)(nil), "message.PlayerCreateGameRequest")
	proto.RegisterType((*PlayerCreateGameResponse)(nil), "message.PlayerCreateGameResponse")
	proto.RegisterType((*PlayerGetMovesRequest)(nil), "message.PlayerGetMovesRequest")
	proto.RegisterType((*PlayerGetMovesResponse)(nil), "message.PlayerGetMovesResponse")
	proto.RegisterType((*PlayerMakeMoveRequest)(nil), "message.PlayerMakeMoveRequest")
	proto.RegisterType((*PlayerMakeMoveResponse)(nil), "message.PlayerMakeMoveResponse")
	proto.RegisterType((*PlayerJoinRequest)(nil), "message.PlayerJoinRequest")
	proto.RegisterType((*PlayerJoinResponse)(nil), "message.PlayerJoinResponse")
	proto.RegisterType((*PlayerOnJoinGameRequest)(nil), "message.PlayerOnJoinGameRequest")
	proto.RegisterType((*PlayerOnJoinGameResponse)(nil), "message.PlayerOnJoinGameResponse")
	proto.RegisterType((*PlayerOnLeaveGameRequest)(nil), "message.PlayerOnLeaveGameRequest")
	proto.RegisterType((*PlayerOnLeaveGameResponse)(nil), "message.PlayerOnLeaveGameResponse")
	proto.RegisterType((*GameJoinRequest)(nil), "message.GameJoinRequest")
	proto.RegisterType((*GameJoinResponse)(nil), "message.GameJoinResponse")
	proto.RegisterType((*GameLeaveRequest)(nil), "message.GameLeaveRequest")
	proto.RegisterType((*GameLeaveResponse)(nil), "message.GameLeaveResponse")
	proto.RegisterType((*GameInfoRequest)(nil), "message.GameInfoRequest")
	proto.RegisterType((*GameInfoResponse)(nil), "message.GameInfoResponse")
	proto.RegisterType((*GameGetMovesRequest)(nil), "message.GameGetMovesRequest")
	proto.RegisterType((*GameGetMovesResponse)(nil), "message.GameGetMovesResponse")
	proto.RegisterType((*GameMakeMoveRequest)(nil), "message.GameMakeMoveRequest")
	proto.RegisterType((*GameMakeMoveResponse)(nil), "message.GameMakeMoveResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 1084 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xb6, 0x12, 0xcb, 0x3f, 0xc7, 0x49, 0xd7, 0x30, 0x89, 0xab, 0x28, 0x49, 0xe7, 0x11, 0x58,
	0xeb, 0xad, 0xab, 0x3b, 0x78, 0xc0, 0x80, 0xa1, 0xe8, 0x50, 0xb7, 0xc5, 0x0c, 0x77, 0x49, 0x5a,
	0xc8, 0xd8, 0xd0, 0x14, 0x03, 0x3a, 0x36, 0x66, 0x3d, 0x63, 0xb1, 0x94, 0x49, 0xb2, 0x17, 0xdf,
	0xef, 0xd1, 0x76, 0xbd, 0x97, 0xd8, 0x8b, 0x14, 0xfc, 0x91, 0x44, 0x91, 0xb2, 0x93, 0xf4, 0x4e,
	0xe4, 0xf9, 0xf8, 0x9d, 0x1f, 0x9e, 0xc3, 0xcf, 0x06, 0x18, 0x93, 0x29, 0xed, 0x5c, 0x84, 0x41,
	0x1c, 0xa0, 0xea, 0x94, 0x46, 0x11, 0x19, 0x53, 0xfc, 0x1a, 0x36, 0x7a, 0x67, 0x71, 0x10, 0xf6,
	0x46, 0xa3, 0x90, 0x46, 0x11, 0x6a, 0xc3, 0x6d, 0x3f, 0x18, 0xd1, 0x77, 0x13, 0x3f, 0x8a, 0x89,
	0x7f, 0x46, 0xdf, 0x4d, 0x46, 0x8e, 0xd5, 0xb2, 0xda, 0x65, 0xef, 0x16, 0xdb, 0x1f, 0xc8, 0xed,
	0xc1, 0x08, 0x35, 0xa1, 0xf2, 0x07, 0xf1, 0x47, 0xe7, 0xd4, 0x59, 0x6b, 0x59, 0xed, 0x4d, 0x4f,
	0xae, 0xf0, 0xbf, 0x16, 0xd4, 0xfa, 0x64, 0x4a, 0x07, 0xfe, 0x87, 0x80, 0x81, 0xf8, 0xb7, 0x20,
	0xa9, 0x7b, 0x95, 0x31, 0x5f, 0x21, 0x04, 0xe5, 0x13, 0x32, 0x15, 0x47, 0xeb, 0x5e, 0xd9, 0x27,
	0x53, 0x8a, 0x76, 0xc0, 0x1e, 0xc6, 0x24, 0xa6, 0xce, 0x7a, 0xcb, 0x6a, 0xdb, 0x9e, 0x1d, 0xb1,
	0x05, 0x72, 0xa1, 0x76, 0x1a, 0xcc, 0xc2, 0xe3, 0x60, 0x4e, 0x9d, 0x72, 0xcb, 0x6a, 0xd7, 0xbc,
	0xda, 0x42, 0xae, 0x51, 0x0b, 0x1a, 0x8c, 0x7d, 0x18, 0x93, 0x30, 0xa6, 0xa1, 0x63, 0x73, 0x73,
	0x63, 0x9c, 0x6d, 0xa1, 0x03, 0xa8, 0xff, 0x12, 0xd1, 0x90, 0xf9, 0x8a, 0x9c, 0x4a, 0x6b, 0xbd,
	0x5d, 0xf7, 0xea, 0xb3, 0x88, 0x86, 0xcc, 0x61, 0xc4, 0xb8, 0x4f, 0x66, 0x53, 0x46, 0x15, 0x39,
	0x55, 0xee, 0xb4, 0xe6, 0xcb, 0x35, 0xbe, 0x07, 0x35, 0xf6, 0x31, 0x8c, 0xe9, 0x05, 0xda, 0x00,
	0xeb, 0x92, 0x27, 0x60, 0x7b, 0xd6, 0x25, 0x5b, 0x2d, 0x78, 0xe0, 0xb6, 0x67, 0x2d, 0x30, 0x81,
	0x3a, 0x8b, 0x81, 0x1f, 0x42, 0x0f, 0xa0, 0x1a, 0xcd, 0xa6, 0x53, 0x12, 0x2e, 0x38, 0xbc, 0xd1,
	0xdd, 0xea, 0xc8, 0x42, 0x77, 0x92, 0x92, 0x78, 0x09, 0x02, 0xdd, 0x07, 0x7b, 0xca, 0x5d, 0xaf,
	0xb5, 0xd6, 0x73, 0xd0, 0xc4, 0xaf, 0x27, 0xec, 0xf8, 0x31, 0x6c, 0xf6, 0xe6, 0x64, 0x72, 0x4e,
	0xde, 0x9f, 0x53, 0x46, 0x73, 0x93, 0xaa, 0xe2, 0xb7, 0xb0, 0x7b, 0x4c, 0x7c, 0x32, 0xa6, 0xe1,
	0x09, 0xfd, 0x9b, 0x9d, 0xf2, 0xe8, 0x5f, 0x33, 0x1a, 0xc5, 0x29, 0x58, 0x50, 0xf0, 0x6f, 0xf4,
	0x10, 0x2a, 0xaf, 0xcf, 0xc9, 0x82, 0x86, 0x9c, 0xa2, 0xd1, 0xdd, 0x4d, 0x63, 0x52, 0x9b, 0xc4,
	0x93, 0x20, 0xec, 0x40, 0x53, 0xe7, 0x8e, 0x2e, 0x02, 0x3f, 0xa2, 0xf8, 0x51, 0xea, 0xb5, 0x4f,
	0x63, 0xd5, 0xab, 0x11, 0xba, 0x58, 0xe1, 0xe7, 0x29, 0x55, 0x7a, 0x40, 0x50, 0xa1, 0xaf, 0xa0,
	0xdc, 0x4f, 0xe2, 0x5c, 0x1a, 0x11, 0x87, 0x28, 0xf1, 0xb0, 0xe5, 0xd1, 0x24, 0x8a, 0xa5, 0x5b,
	0xdc, 0x87, 0x3b, 0x86, 0x45, 0xf2, 0x7f, 0x03, 0x76, 0x9f, 0xb7, 0x87, 0xc5, 0xaf, 0xa1, 0x99,
	0x39, 0x50, 0x6b, 0xee, 0x09, 0x10, 0xfe, 0x36, 0x75, 0xf1, 0x53, 0x48, 0xe9, 0x75, 0x32, 0xdb,
	0x4b, 0x5d, 0x67, 0x27, 0x64, 0x95, 0xbe, 0x86, 0x1d, 0x51, 0xc9, 0x21, 0x8d, 0x4f, 0xf2, 0x57,
	0xe3, 0x2b, 0x57, 0xc3, 0xef, 0xf1, 0x0e, 0xec, 0x6a, 0x58, 0x49, 0xb2, 0x03, 0x48, 0x18, 0x06,
	0xfe, 0x88, 0x5e, 0x26, 0x09, 0xcf, 0x61, 0x3b, 0xb7, 0x2b, 0x93, 0xbd, 0x9f, 0x4f, 0xb6, 0xa0,
	0x3d, 0xed, 0x31, 0x1f, 0x8d, 0xef, 0x01, 0xd2, 0xfc, 0x93, 0x0e, 0x5d, 0x56, 0x1a, 0x20, 0x29,
	0x92, 0x65, 0x2b, 0xfc, 0x3e, 0x0f, 0x29, 0x89, 0xd5, 0x02, 0x61, 0x17, 0x1c, 0xd3, 0x94, 0xf5,
	0x8b, 0xb0, 0xf5, 0x69, 0xcc, 0x47, 0xe9, 0xaa, 0xaa, 0x3e, 0x83, 0xa6, 0x7e, 0x40, 0xa6, 0xd8,
	0x4e, 0xc6, 0x4a, 0x34, 0x0c, 0xca, 0xa5, 0x28, 0xa0, 0x72, 0xae, 0x7e, 0x4e, 0x9c, 0x1e, 0x93,
	0x3f, 0xb9, 0xe5, 0x0a, 0xa7, 0x6c, 0xf2, 0xdf, 0x24, 0x93, 0xff, 0x86, 0xad, 0x4e, 0xe5, 0x5b,
	0x65, 0x9d, 0xb2, 0xde, 0xd3, 0xc9, 0x64, 0x6e, 0x0f, 0x60, 0x4b, 0x58, 0x5e, 0x06, 0x13, 0xff,
	0xaa, 0xbc, 0xd2, 0xdb, 0x14, 0x60, 0x49, 0xf1, 0x5b, 0x52, 0xd5, 0x57, 0x3e, 0xdb, 0xbf, 0x46,
	0xdb, 0xb1, 0xb1, 0x61, 0xc3, 0xb1, 0x7a, 0x90, 0x39, 0x04, 0x77, 0x92, 0x8b, 0x51, 0xd9, 0x65,
	0x35, 0x0b, 0x5e, 0x09, 0xdc, 0xcd, 0xf0, 0x47, 0x94, 0xcc, 0xaf, 0x35, 0x05, 0xfb, 0xb0, 0x57,
	0x70, 0x46, 0xa6, 0xf7, 0x14, 0x3e, 0x63, 0x6b, 0xb5, 0x3e, 0x0f, 0xa1, 0x72, 0x21, 0x5e, 0xa2,
	0x95, 0x73, 0x2f, 0x41, 0x18, 0xc1, 0xed, 0x8c, 0x41, 0xb2, 0xf6, 0xc4, 0x1e, 0x77, 0xf7, 0x89,
	0xb4, 0xdb, 0xb0, 0xa5, 0x50, 0xe4, 0xa3, 0xe5, 0xd3, 0xf2, 0x69, 0xb4, 0x3f, 0x88, 0xc8, 0x04,
	0x83, 0x2c, 0xf4, 0x97, 0x50, 0x1e, 0x67, 0xcf, 0x5c, 0xc1, 0x60, 0x72, 0x33, 0x7e, 0x01, 0xdb,
	0x6c, 0x47, 0x1f, 0x93, 0x1b, 0x06, 0xf0, 0x23, 0xec, 0xe4, 0x59, 0x64, 0x10, 0xf7, 0xa0, 0x3c,
	0xf1, 0x3f, 0x04, 0x2b, 0x46, 0x87, 0xdb, 0xf1, 0xef, 0x22, 0x0a, 0x7d, 0x6e, 0x6e, 0x16, 0x85,
	0x90, 0xd5, 0xb5, 0x9c, 0xac, 0xae, 0x27, 0xb2, 0xda, 0x14, 0x11, 0xea, 0xc3, 0xd4, 0xfd, 0x6f,
	0x0d, 0x6e, 0xc9, 0xe7, 0x74, 0x48, 0xc3, 0xf9, 0xe4, 0x8c, 0xa2, 0x23, 0xa8, 0x4a, 0xf9, 0x41,
	0x77, 0x33, 0x0d, 0x2d, 0xd2, 0x3c, 0xf7, 0xf3, 0xa5, 0x76, 0x79, 0xb7, 0x25, 0xc6, 0x26, 0x15,
	0xc8, 0x64, 0xcb, 0x6b, 0x99, 0xc9, 0xa6, 0x49, 0x17, 0x2e, 0xa1, 0x57, 0xe2, 0xb7, 0x10, 0x13,
	0x1c, 0x64, 0xc2, 0xf3, 0x22, 0xe5, 0xb6, 0x96, 0x03, 0x54, 0xc2, 0x44, 0x46, 0x4c, 0x42, 0x4d,
	0x92, 0x4c, 0x42, 0x43, 0x81, 0x4a, 0xdd, 0x7f, 0x6c, 0xd8, 0x4c, 0x84, 0x45, 0xd4, 0xf3, 0x25,
	0x54, 0xa5, 0xc6, 0xa0, 0xc3, 0x94, 0xa0, 0x48, 0xa7, 0xdc, 0xbb, 0xcb, 0xcc, 0x69, 0xb8, 0x2f,
	0xc0, 0xe6, 0x02, 0x84, 0xf6, 0x35, 0xa8, 0x2a, 0x56, 0xee, 0x41, 0xb1, 0x31, 0x65, 0x19, 0x02,
	0x64, 0x9a, 0x81, 0x5a, 0x1a, 0xda, 0x50, 0x1a, 0xf7, 0x8b, 0x15, 0x88, 0x94, 0xf4, 0x18, 0x6a,
	0x49, 0xff, 0x23, 0x3d, 0x11, 0x6d, 0xbc, 0x94, 0x9b, 0x2e, 0x16, 0x1d, 0x41, 0x97, 0x34, 0xab,
	0x41, 0xa7, 0xcd, 0x89, 0x41, 0x67, 0x48, 0x46, 0x09, 0xf5, 0xa0, 0xcc, 0x1e, 0x33, 0xe4, 0x6a,
	0x50, 0xe5, 0x8d, 0x74, 0xf7, 0x0b, 0x6d, 0x6a, 0xd5, 0xb2, 0x07, 0xdd, 0xa8, 0x9a, 0xa1, 0x24,
	0x46, 0xd5, 0x4c, 0x35, 0xc0, 0x25, 0xf4, 0x2b, 0x34, 0x94, 0x17, 0x1c, 0x99, 0x67, 0x74, 0x45,
	0x70, 0xf1, 0x2a, 0x48, 0xda, 0x86, 0xff, 0xaf, 0xc9, 0xdf, 0xf2, 0xb2, 0x09, 0x9f, 0xc8, 0xfc,
	0x9d, 0xdc, 0x1b, 0xa4, 0x66, 0xbf, 0x57, 0x60, 0x49, 0xc3, 0x7c, 0x0a, 0x36, 0xf7, 0x82, 0xf2,
	0x28, 0x55, 0x0b, 0x5c, 0xb7, 0xc8, 0x94, 0x32, 0x3c, 0x81, 0x32, 0xff, 0x07, 0xe3, 0x98, 0x2f,
	0x71, 0x61, 0x00, 0xea, 0x63, 0x8e, 0x4b, 0x68, 0xa0, 0x74, 0xd7, 0x41, 0x0e, 0xa8, 0xf7, 0xd6,
	0xe1, 0x12, 0xab, 0x4a, 0x95, 0x76, 0x56, 0x9e, 0x4a, 0xef, 0xab, 0xc3, 0x25, 0xd6, 0x84, 0xea,
	0xd9, 0xc6, 0x5b, 0xe8, 0x3c, 0x7a, 0x2c, 0x41, 0xef, 0x2b, 0xfc, 0xbf, 0xe0, 0x77, 0x1f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x48, 0x33, 0x34, 0xcf, 0x19, 0x0e, 0x00, 0x00,
}
