// Code generated by protoc-gen-goactor. DO NOT EDIT.
// source: hello.proto

package hello

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	go_actor "github.com/lsg2020/go-actor"
)

// HelloServiceInterface is the server API for HelloService service.
type HelloServiceInterface interface {
	// SEND;test send protocol
	OnSend(*go_actor.DispatchMessage, *Request) error
	OnAdd(*go_actor.DispatchMessage, *Request) (*Response, error)
	OnTestCallAdd(*go_actor.DispatchMessage, *Request) (*Response, error)
}

func RegisterHelloService(s HelloServiceInterface, proto go_actor.Proto) {
	reg := &HelloServiceProto{s: s}
	reg.register(proto)
}
func NewHelloServiceClient(proto go_actor.Proto) *HelloServiceClient {
	client := &HelloServiceClient{Proto: proto}
	return client
}

type HelloServiceProto struct {
	s HelloServiceInterface
}

func (s *HelloServiceProto) register(p go_actor.Proto) {
	p.Register(
		"HelloService.Send",
		func(ctx *go_actor.DispatchMessage, args ...interface{}) error {
			err := s.s.OnSend(ctx, args[0].(*Request))
			if err != nil {
				ctx.System.Logger().Errorf("message process error:%#v", err.Error())
			}
			return err
		},
		func() proto.Message { return new(Request) },
		func() proto.Message { return new(Empty) },
	)

	p.Register(
		"HelloService.Add",
		func(ctx *go_actor.DispatchMessage, args ...interface{}) error {
			rsp, err := s.s.OnAdd(ctx, args[0].(*Request))

			if err != nil {
				ctx.Response(err, nil)
			} else {
				ctx.Response(nil, rsp)
			}
			return nil
		},
		func() proto.Message { return new(Request) },
		func() proto.Message { return new(Response) },
	)

	p.Register(
		"HelloService.TestCallAdd",
		func(ctx *go_actor.DispatchMessage, args ...interface{}) error {
			rsp, err := s.s.OnTestCallAdd(ctx, args[0].(*Request))

			if err != nil {
				ctx.Response(err, nil)
			} else {
				ctx.Response(nil, rsp)
			}
			return nil
		},
		func() proto.Message { return new(Request) },
		func() proto.Message { return new(Response) },
	)

}

type HelloServiceClient struct {
	Proto go_actor.Proto
}

func (client *HelloServiceClient) Send(system *go_actor.ActorSystem, actor go_actor.Actor, dest *go_actor.ActorAddr, req *Request, options *go_actor.CallOptions) error {
	err := actor.SendProto(system, dest, client.Proto.Id(), options, "HelloService.Send", req)

	return err
}

func (client *HelloServiceClient) Add(ctx context.Context, system *go_actor.ActorSystem, actor go_actor.Actor, dest *go_actor.ActorAddr, req *Request, options *go_actor.CallOptions) (*Response, error) {
	rsp, err := actor.CallProto(ctx, system, dest, client.Proto.Id(), options, "HelloService.Add", req)

	if err != nil {
		return nil, err
	}
	return rsp[0].(*Response), nil
}

func (client *HelloServiceClient) TestCallAdd(ctx context.Context, system *go_actor.ActorSystem, actor go_actor.Actor, dest *go_actor.ActorAddr, req *Request, options *go_actor.CallOptions) (*Response, error) {
	rsp, err := actor.CallProto(ctx, system, dest, client.Proto.Id(), options, "HelloService.TestCallAdd", req)

	if err != nil {
		return nil, err
	}
	return rsp[0].(*Response), nil
}
