// Code generated by protoc-gen-gactor. DO NOT EDIT.
// source: hello.proto

package hello

import (
	context "context"
	gactor "github.com/lsg2020/gactor"
	proto "google.golang.org/protobuf/proto"
)

// HelloServiceInterface is the server API for HelloService service.
type HelloServiceInterface interface {
	// onlysend
	OnSend(*gactor.DispatchMessage, *Request) *gactor.ActorError
	OnAdd(*gactor.DispatchMessage, *Request) (*Response, *gactor.ActorError)
	OnCallSourceAdd(*gactor.DispatchMessage, *Request) (*Response, *gactor.ActorError)
}

func NewHelloServiceServer(s HelloServiceInterface, proto gactor.Proto) *HelloServiceServer {
	server := &HelloServiceServer{s: s}
	server.register(proto)
	return server
}
func NewHelloServiceClient(proto gactor.Proto) *HelloServiceClient {
	client := &HelloServiceClient{Proto: proto}
	return client
}

type HelloServiceServer struct {
	s HelloServiceInterface
}

func (s *HelloServiceServer) register(p gactor.Proto) {
	p.Register(
		"HelloService.Send",
		func(ctx *gactor.DispatchMessage, args ...interface{}) {
			err := s.s.OnSend(ctx, args[0].(*Request))
			if err != nil {
				ctx.System.Logger().Errorf("message process error:%#v", err.Error())
			}
		},
		func() proto.Message { return new(Request) },
		func() proto.Message { return new(Empty) },
	)

	p.Register(
		"HelloService.Add",
		func(ctx *gactor.DispatchMessage, args ...interface{}) {
			rsp, err := s.s.OnAdd(ctx, args[0].(*Request))

			if err != nil {
				ctx.Response(err, nil)
			} else {
				ctx.Response(nil, rsp)
			}
		},
		func() proto.Message { return new(Request) },
		func() proto.Message { return new(Response) },
	)

	p.Register(
		"HelloService.CallSourceAdd",
		func(ctx *gactor.DispatchMessage, args ...interface{}) {
			rsp, err := s.s.OnCallSourceAdd(ctx, args[0].(*Request))

			if err != nil {
				ctx.Response(err, nil)
			} else {
				ctx.Response(nil, rsp)
			}
		},
		func() proto.Message { return new(Request) },
		func() proto.Message { return new(Response) },
	)

}

type HelloServiceClient struct {
	Proto gactor.Proto
}

func (client *HelloServiceClient) Send(system *gactor.ActorSystem, actor gactor.Actor, dest *gactor.ActorAddr, req *Request, options gactor.Headers) *gactor.ActorError {
	err := actor.SendProto(system, dest, client.Proto.Id(), options, "HelloService.Send", req)

	return err
}

func (client *HelloServiceClient) Add(ctx context.Context, system *gactor.ActorSystem, actor gactor.Actor, dest *gactor.ActorAddr, req *Request, options gactor.Headers) (*Response, *gactor.ActorError) {
	rsp, err := actor.CallProto(ctx, system, dest, client.Proto.Id(), options, "HelloService.Add", req)

	if err != nil {
		return nil, err
	}
	return rsp[0].(*Response), nil
}

func (client *HelloServiceClient) CallSourceAdd(ctx context.Context, system *gactor.ActorSystem, actor gactor.Actor, dest *gactor.ActorAddr, req *Request, options gactor.Headers) (*Response, *gactor.ActorError) {
	rsp, err := actor.CallProto(ctx, system, dest, client.Proto.Id(), options, "HelloService.CallSourceAdd", req)

	if err != nil {
		return nil, err
	}
	return rsp[0].(*Response), nil
}
