// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remote.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ActorAddr struct {
	NodeInstanceId       uint64   `protobuf:"varint,1,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	Handle               uint32   `protobuf:"varint,2,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorAddr) Reset()         { *m = ActorAddr{} }
func (m *ActorAddr) String() string { return proto.CompactTextString(m) }
func (*ActorAddr) ProtoMessage()    {}
func (*ActorAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{1}
}

func (m *ActorAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorAddr.Unmarshal(m, b)
}
func (m *ActorAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorAddr.Marshal(b, m, deterministic)
}
func (m *ActorAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorAddr.Merge(m, src)
}
func (m *ActorAddr) XXX_Size() int {
	return xxx_messageInfo_ActorAddr.Size(m)
}
func (m *ActorAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ActorAddr proto.InternalMessageInfo

func (m *ActorAddr) GetNodeInstanceId() uint64 {
	if m != nil {
		return m.NodeInstanceId
	}
	return 0
}

func (m *ActorAddr) GetHandle() uint32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type Header struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32      `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ValInt               int32      `protobuf:"varint,3,opt,name=val_int,json=valInt,proto3" json:"val_int,omitempty"`
	ValString            string     `protobuf:"bytes,4,opt,name=val_string,json=valString,proto3" json:"val_string,omitempty"`
	ValAddr              *ActorAddr `protobuf:"bytes,5,opt,name=val_addr,json=valAddr,proto3" json:"val_addr,omitempty"`
	ValBytes             []byte     `protobuf:"bytes,6,opt,name=val_bytes,json=valBytes,proto3" json:"val_bytes,omitempty"`
	ValUint64            uint64     `protobuf:"varint,7,opt,name=val_uint64,json=valUint64,proto3" json:"val_uint64,omitempty"`
	ValInt64             int64      `protobuf:"varint,8,opt,name=val_int64,json=valInt64,proto3" json:"val_int64,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{2}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Header) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Header) GetValInt() int32 {
	if m != nil {
		return m.ValInt
	}
	return 0
}

func (m *Header) GetValString() string {
	if m != nil {
		return m.ValString
	}
	return ""
}

func (m *Header) GetValAddr() *ActorAddr {
	if m != nil {
		return m.ValAddr
	}
	return nil
}

func (m *Header) GetValBytes() []byte {
	if m != nil {
		return m.ValBytes
	}
	return nil
}

func (m *Header) GetValUint64() uint64 {
	if m != nil {
		return m.ValUint64
	}
	return 0
}

func (m *Header) GetValInt64() int64 {
	if m != nil {
		return m.ValInt64
	}
	return 0
}

type Message struct {
	Headers              []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	ResponseErr          *Error    `protobuf:"bytes,2,opt,name=response_err,json=responseErr,proto3" json:"response_err,omitempty"`
	Payload              []byte    `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Message) GetResponseErr() *Error {
	if m != nil {
		return m.ResponseErr
	}
	return nil
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "message.Error")
	proto.RegisterType((*ActorAddr)(nil), "message.ActorAddr")
	proto.RegisterType((*Header)(nil), "message.Header")
	proto.RegisterType((*Message)(nil), "message.Message")
}

func init() { proto.RegisterFile("remote.proto", fileDescriptor_eefc82927d57d89b) }

var fileDescriptor_eefc82927d57d89b = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x92, 0x31, 0xcb, 0xdb, 0x30,
	0x10, 0x86, 0x51, 0x1c, 0xdb, 0x9f, 0xcf, 0x69, 0xfa, 0xa1, 0xa1, 0x15, 0x94, 0x82, 0xf1, 0xe4,
	0x0e, 0x31, 0x34, 0x2d, 0x5d, 0x3a, 0x25, 0x10, 0xa8, 0x87, 0x2c, 0x2a, 0x5d, 0xba, 0x18, 0x25,
	0x12, 0x89, 0xc1, 0x91, 0x8c, 0xa4, 0x06, 0x32, 0xf6, 0xff, 0xf6, 0x47, 0x14, 0x9d, 0xed, 0x6c,
	0x77, 0xef, 0xdd, 0x23, 0xdd, 0x7b, 0x12, 0xac, 0xac, 0xba, 0x19, 0xaf, 0xea, 0xc1, 0x1a, 0x6f,
	0x68, 0x7a, 0x53, 0xce, 0x89, 0x8b, 0x2a, 0x37, 0x10, 0x1f, 0xac, 0x35, 0x96, 0x52, 0x58, 0x9e,
	0x8d, 0x54, 0x8c, 0x14, 0xa4, 0x8a, 0x39, 0xc6, 0xf4, 0x15, 0xa2, 0x9b, 0xbb, 0xb0, 0x45, 0x41,
	0xaa, 0x8c, 0x87, 0xb0, 0x3c, 0x42, 0xb6, 0x3b, 0x7b, 0x63, 0x77, 0x52, 0x5a, 0x5a, 0xc1, 0xab,
	0x36, 0x52, 0xb5, 0x9d, 0x76, 0x5e, 0xe8, 0xb3, 0x6a, 0x3b, 0x89, 0xf8, 0x92, 0xaf, 0x83, 0xde,
	0x4c, 0x72, 0x23, 0xe9, 0x3b, 0x48, 0xae, 0x42, 0xcb, 0x5e, 0xe1, 0x59, 0x6f, 0xf8, 0x94, 0x95,
	0xff, 0x08, 0x24, 0x3f, 0x94, 0x90, 0xca, 0xd2, 0x35, 0x2c, 0x26, 0x3c, 0xe6, 0x8b, 0x4e, 0x86,
	0x79, 0xfc, 0x63, 0x18, 0x81, 0x98, 0x63, 0x4c, 0xdf, 0x43, 0x7a, 0x17, 0x7d, 0xdb, 0x69, 0xcf,
	0x22, 0x94, 0x93, 0xbb, 0xe8, 0x1b, 0xed, 0xe9, 0x47, 0x80, 0x50, 0x70, 0xde, 0x76, 0xfa, 0xc2,
	0x96, 0x38, 0x6f, 0x76, 0x17, 0xfd, 0x4f, 0x14, 0xe8, 0x06, 0x5e, 0x42, 0x59, 0x48, 0x69, 0x59,
	0x5c, 0x90, 0x2a, 0xdf, 0xd2, 0x7a, 0x5a, 0x40, 0xfd, 0xb4, 0xc3, 0xc3, 0xd9, 0xe8, 0xeb, 0x03,
	0x04, 0xb6, 0x3d, 0x3d, 0xbc, 0x72, 0x2c, 0x29, 0x48, 0xb5, 0xe2, 0x81, 0xdf, 0x87, 0x7c, 0xbe,
	0xea, 0x4f, 0xa7, 0xfd, 0xb7, 0xaf, 0x2c, 0x45, 0xbb, 0xa1, 0xfd, 0x17, 0x0a, 0x33, 0x3b, 0x56,
	0x5f, 0x0a, 0x52, 0x45, 0xc8, 0x36, 0x21, 0x2f, 0xff, 0x12, 0x48, 0x8f, 0xe3, 0xbd, 0xf4, 0x13,
	0xa4, 0x57, 0x74, 0xee, 0x18, 0x29, 0xa2, 0x2a, 0xdf, 0xbe, 0x7d, 0x8e, 0x34, 0x6e, 0x84, 0xcf,
	0x75, 0xfa, 0x39, 0x3c, 0x9e, 0x1b, 0x8c, 0x76, 0xaa, 0x55, 0xd6, 0xe2, 0x4a, 0xf2, 0xed, 0xfa,
	0xd9, 0x8f, 0x0f, 0xc8, 0xf3, 0xb9, 0xe7, 0x60, 0x2d, 0x65, 0x90, 0x0e, 0xe2, 0xd1, 0x1b, 0x21,
	0xd9, 0x0a, 0x0d, 0xcc, 0xe9, 0x3e, 0xff, 0x9d, 0xd5, 0xdf, 0x27, 0xf2, 0x94, 0xe0, 0x6f, 0xf8,
	0xf2, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x52, 0xe2, 0xa5, 0x98, 0x1d, 0x02, 0x00, 0x00,
}
